# -*- coding: utf-8 -*-
"""A98591_S22B23_001_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPdx7ws4W5dzJgSYpVbtcKcxWHPg5fjD
"""

# QUESTION ONE : RESTAURANT MENUE MANAGEMENT

menu = {
    'burger': 25,
    'pizza': 38,
    'salad': 34,
}

def calculate_order_total(items, memo={}):
    if not items:
        return 0

    items.sort()  # Here I just used this function to Sort the items to create a consistent key for memoization.
    key = tuple(items) # here we have just converted our items list into tuple.

    if key in memo: # now checking if the key is stored in the memo dictionary
        return memo[key]

    total_cost = 0 # then I initiate the total cost to zero.
    for item in items:
        if item in menu:
            total_cost += menu[item]

    memo[key] = total_cost
    return total_cost

# Example usage
order1 = ['burger', 'pizza', 'salad']
order2 = ['burger', 'burger', 'pizza', 'salad']

total_cost1 = calculate_order_total(order1)
total_cost2 = calculate_order_total(order2)

print(f"Total cost for order 1: ${total_cost1}")
print(f"Total cost for order 2: ${total_cost2}")


##############################################################################################################
